version: "3.7"

networks:
  playground:
    driver: bridge

services:

  ansible-target:
    image: ansible-target
    build: ansible-target
    container_name: ansible-target
    networks:
      - playground
    ports:
      - "6022:22"
      - "6880:8080"
      - "6080:80"
      - "6443:443"
      - "64502:4502"
    volumes:
      - ./artifacts:/artifacts
    privileged: true
    hostname: ansible-target