version: "3.7"

networks:
  playground:
    driver: bridge

services:

  author:
    image: ansible-base
    build: ansible-base
    container_name: author
    networks:
      - playground
    ports:
      - "6010:22"
      - "6020:443"
      - "6030:4502"
    privileged: true
    hostname: author

  publish:
    image: ansible-base
    build: ansible-base
    container_name: publish
    networks:
      - playground
    ports:
      - "6011:22"
      - "6021:443"
      - "6031:4502"
    privileged: true
    hostname: publish

  dispatcher:
    image: ansible-base
    build: ansible-base
    container_name: dispatcher
    networks:
      - playground
    ports:
      - "6012:22"
      - "6022:443"
    privileged: true
    hostname: dispatcher