---

- name: Generate private key
  command: openssl genrsa -out {{ host }}.key 2048
  args:
    chdir: "{{ ssl_dir.path }}"

- name: Convert key to DER
  command: openssl pkcs8 -topk8 -inform PEM -in {{ host }}.key -outform DER -out {{ host }}.der -nocrypt
  args:
    chdir: "{{ ssl_dir.path }}"

- name: Generate CSR
  command: openssl req -new -key {{ host }}.key -out {{ host }}.csr -subj "/C=LU/ST=Luxembourg/L=Betrange/O=theopendle/CN={{ host }}.aem.deployment"
  args:
    chdir: "{{ ssl_dir.path }}"

- name: Create extfile
  template:
    src: ../templates/extfile.ext.j2
    dest: "{{ ssl_dir.path }}/extfile-{{ host }}.ext"

- name: Create certificate
  command: openssl x509 -req -in {{ host }}.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out {{ host }}.crt -days 825 -sha256 -passin pass:ca123 -extfile extfile-{{ host }}.ext
  args:
    chdir: "{{ ssl_dir.path }}"

- name: Copy objects to container
  shell: |
    sshpass -p 'root' scp -o StrictHostKeyChecking=no {{ host }}.key root@{{ host }}:/etc/pki/tls/private/aem.key
    sshpass -p 'root' scp -o StrictHostKeyChecking=no {{ host }}.der root@{{ host }}:/etc/pki/tls/private/aem.der
    sshpass -p 'root' scp -o StrictHostKeyChecking=no {{ host }}.crt root@{{ host }}:/etc/pki/tls/certs/aem.crt
  args:
    chdir: "{{ ssl_dir.path }}"