---
- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - httpd
    - mod_ssl

- name: Copy dispatcher module
  copy: 
    src:
    dest:
  register: dispatcher_so
  tags:
    - aem
    - never

- name: Create symlink for Dispatcher module in /etc
  file:
    src: "{{ dtp_aem_opt_root }}/dispatcher/dispatcher-apache2.4-{{ dtp_dispatcher_version }}.so"
    dest: "/etc/httpd/modules/mod_dispatcher.so"
    state: link
  tags:
    - aem
    - never

- name: Create symlinks for SSL crt
  file:
    src: "{{ dtp_aem_opt_root }}/author/ssl/localhost.crt"
    dest: "{{ dtp_aem_opt_root }}/dispatcher/httpd/conf.d/dispatcher/ssl/aem_server.crt"
    state: link
  tags:
    - aem
    - never

- name: Create symlinks for SSL key
  file:
    src: "{{ dtp_aem_opt_root }}/author/ssl/localhostprivate.key"
    dest: "{{ dtp_aem_opt_root }}/dispatcher/httpd/conf.d/dispatcher/ssl/aem_server.key"
    state: link
  tags:
    - aem
    - never

- name: Set permisisons on installation directory
  become: yes
  shell: |
    chown -R {{ devtop_owner_username }}:apache {{ dtp_aem_opt_root }}/dispatcher
    chmod -R 775 {{ dtp_aem_opt_root }}/dispatcher
  args:
    warn: no
  tags:
    - aem
    - never

- name: Check if default SSL conf exists
  stat: 
    path: /etc/httpd/conf.d/ssl.conf
  register: ssl
  tags:
    - aem
    - never

- name: Disable default SSL conf
  when: ssl.stat.exists
  command: mv /etc/httpd/conf.d/ssl.conf /etc/httpd/conf.d/ssl.conf.disabled
  tags:
    - aem
    - never

- name: Deactivate default HTTP port
  replace: 
    path: /etc/httpd/conf/httpd.conf 
    regexp: '^Listen 80'
    replace: '#Listen 80'
  tags:
    - aem
    - never