---
- name: Unlock CRXDE
  uri:
    url: http://localhost:{{ aem_port }}/apps/system/config/org.apache.sling.jcr.davex.impl.servlets.SlingDavExServlet
    user: admin
    password: "{{ aem_admin_password }}"
    method: POST
    body_format: form-urlencoded
    return_content: true
    status_code: 
      - 200
      - 201
    body:
      "jcr:primaryType": sling:OsgiConfig
      "alias": /crx/server
      "dav.create-absolute-uri": true
      "dav.create-absolute-uri@TypeHint": Boolean

- name: Configure SSL
  command: |
    curl -u admin:{{ aem_admin_password }} \
    -F "keystorePassword={{ aem_admin_password }}" \
    -F "keystorePasswordConfirm={{ aem_admin_password }}" \
    -F "truststorePassword={{ aem_admin_password }}" \
    -F "truststorePasswordConfirm={{ aem_admin_password }}" \
    -F "privatekeyFile=@/etc/pki/tls/private/aem.der" \
    -F "certificateFile=@/etc/pki/tls/certs/aem.crt" \
    -F "httpsHostname={{ ansible_fqdn }}.aem.deployment" \
    -F "httpsPort={{ aem_secure_port }}" \
    http://localhost:{{ aem_port }}/libs/granite/security/post/sslSetup.html
  retries: 3
  delay: 10
  register: configure_ssl
  until: configure_ssl.rc == 0

- name: Check SSL connection
  uri:
    url: "https://{{ ansible_fqdn }}.aem.deployment:{{ aem_secure_port }}/libs/granite/core/content/login.html"
    status_code: 200
    validate_certs: no