- become: true
  become_user: root
  block:

  - name: Create the AEM init script
    become: yes
    template:
      src: "../templates/aem/init.j2"
      dest: "/usr/bin/aem"
      mode: '0755'

  - name: Create the AEM service
    become: yes
    template:
      src: "../templates/aem/service.j2"
      dest: /etc/systemd/system/aem.service
      mode: '0755'

  - name: "Allow aem user to run aem service"
    template:
      src: "../templates/aem/sudoers.j2"
      dest: /etc/sudoers.d/aem
      mode: '0440'