---
- name: Create temp SSL dir
  file:
    path: "{{ ssl_temp_dir }}"
    state: directory

- name: Generate CA key
  command: openssl genrsa -des3 -passout pass:{{ ssl_ca_password }} -out {{ ssl_ca_name }}.key 2048
  args:
    chdir: "{{ ssl_temp_dir }}"

- name: Generate CA root certificate
  command: openssl req -x509 -new -nodes -key {{ ssl_ca_name }}.key -sha256 -days 1825 -passin pass:{{ ssl_ca_password }} -out {{ ssl_ca_name }}.crt -subj "/C=LU/ST=Luxembourg/L=Betrange/O=theopendle/CN={{ ssl_ca_name }}"
  args:
    chdir: "{{ ssl_temp_dir }}"

- when: ssl_update_host_ca
  become: true
  block:

  - name: Copy CA to trusted certs directory
    copy:
      remote_src: true
      src: "{{ ssl_temp_dir }}/{{ ssl_ca_name }}.crt"
      dest: "{{ ssl_ca_dir }}"

  - name: Update truststore
    command: update-ca-certificates

- include_tasks: tasks/create_container_crypto_objects.yaml
  loop: "{{ groups['aem'] }}"
  loop_control:
    loop_var: host

- name: Delete temp SSL directory
  file:
    path: "{{ ssl_temp_dir }}"
    state: absent