---
- hosts: all
  become: true
  vars_files:
    - vars.yaml

  tasks:
    - name: Stop AEM
      command: bash {{ aem_install_dir }}/crx-quickstart/bin/stop
      async: 45
      poll: 0

    - name: Wait until the instance is stopped
      wait_for:
        port: "{{ aem_port }}"
        state: stopped